title: Matkul HKPDD (Desentralisasi Fiskal)
lang: id
description: Laman web untuk mata kuliah Hubungan Keuangan Pusat, Daerah dan Desa (Desentralisasi Fiskal) PKN STAN

theme: null

edit: true
addons_branch: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  revision: true

readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - jekyll-rtd-theme.gemspec
